const PREFIX = 'PWM_';

export const StorageVars = {
    "DELETED_PASSWORDS": PREFIX + "DELETED_PASSWORDS",
    "SYNC_MODE": PREFIX + "SYNC_MODE",
    "TOKEN": PREFIX + "TOKEN",
    "USER": PREFIX + "USER",
    "TEST_ITEM": PREFIX + "TEST_ITEM",
    "TRIES": PREFIX + "TRIES",
    "PW": PREFIX + "PW",
    "BOOKMARKS": PREFIX + 'BOOKMARKS',
};